# Generated by Django 5.1.6 on 2025-03-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(max_length=20, verbose_name='رمز الخدمة')),
                ('patient_id', models.CharField(max_length=20, verbose_name='رقم الهوية / الإقامة')),
                ('patient_name', models.CharField(max_length=100, verbose_name='اسم المريض')),
                ('sick_leave_date', models.DateField(verbose_name='تاريخ إصدار الإجازة')),
                ('duration', models.IntegerField(verbose_name='مدة الإجازة بالأيام')),
                ('date_from', models.DateField(verbose_name='تبدأ من')),
                ('date_to', models.DateField(verbose_name='تنتهي في')),
                ('doctor_name', models.CharField(max_length=100, verbose_name='اسم الطبيب')),
                ('job_title', models.CharField(max_length=100, verbose_name='المسمى الوظيفي')),
            ],
        ),
    ]
